specVersion: 1.0.0
name: sora-subquery-dictionary
version: 1.0.0
runner:
  node:
    name: '@subql/node'
    version: '*'
    options:
      unfinalizedBlocks: false
      historical: false
  query:
    name: '@subql/query'
    version: '*'
description: ''
repository: https://github.com/sora-xor/sora-subquery
schema:
  file: ./schema.graphql
network:
  chainId: '0x7e4e32d0feafd4f9c9414b0be86373f9a1efa904809b683453a9af6856d38ad5'
  endpoint: wss://mof3.sora.org
  chaintypes:
    file: ./types.json
dataSources:
  - kind: substrate/Runtime
    startBlock: 1 # substrate 4 start block
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
